# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sdm845-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),crownqlte star2qlte starqlte crownqltechn starqltechn star2qltechn)

endif
